language: node_js
sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
node_js:
- stable
- 7
- 6
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- export DISPLAY=:99.0
- export CHROME_BIN=chromium-browser
- sh -e /etc/init.d/xvfb start
- sleep 3
after_success:
- npm run coverage
- npm run build
deploy:
  provider: npm
  skip_cleanup: true
  email: develop@uncovertruth.co.jp
  api_key:
    secure: cUCAHlNojvq1lCc7v56jW0/Gg7dyu4f5eb4zn0+b+TGcWLxviAX1tQip66si3ONQOgocjkUvTZrZhkDRSlOZgbw4iRM0KtK8uO6VfIcqAf3ZnLKmVfTH2x6lREGiPm2zCVpDjUsQR34qOqiU1bMybPTFq8148J9EnxC1L1TMsjTpQxn4gSB9To7EwQNmKUVX9vaRGsZQ/CRmM1Xt5qaqiEUUbNf95dfHr+kcGJN3/rnYGtWXtfbJH2WZhBrvpCBrUILj4lUTsf5s53dOIvU8CiT0Wtb9llSzE7aK0/6PlYtMvxyN9xbgrgixil4fPw6LJlCLLmX5+dw7eOTqHNPJy7YjZms798FJxT9eta3K6/cD209Jy3DXKBYjX308+hFrUB8PfCkYJWm0GTW2ksjdwxQK4XnagidQeDzZHD2sYrI1TuYa666DTYSXTkGCpWBwIqfooXtoa90ELxtcsOToBpOLfu+qpgGE8EDsViqYtDwnakM0rnbIc+abZgyauLvEnrWbvS16euQyi4jOo6bUA8vWXZJVQGi27UENBsoxkN4BgGoFaUbSOVSuCx97pRte4oeB4VPGjz9I0nSfj3Mgap0WmfEQaBqmAmagx0VLoRrUl50sRR8Vj+IZys9DxN4Qf80Y+wbKVgiQyeWqzCcTL2fEC25iRV3TEIJ9Y1WoXYg=
  on:
    tags: true
    repo: userdive/userdive.js
notifications:
  email: false
  slack:
    rooms:
      secure: Dj38r8d0sfrvP+tEGFQnyRjH+dRYsCw42o6P5S8pCWLA6dZCAyRVehUfYDsYBcy6dDNsPBU+u9p285KBpf4vKOmSa8RX22HkqtCHa/xQPhp+hvqziwxplMPuo6JO4ebs+UVwD+i3KLtRheaRE8Q2aXtTj4ZbVRIeIjtCaIzT6cnNWjqPqe6j8hAJYvyoV5XW96iZaHPeWViaQcJtN7jG9Ml41EEqNlPpxO6mam6Ccr15AG5+Ih3epGCrLGiKxPrGL/X3/ehu9xvfDlXfgTyiZP3M/bTeaa59DwdF7ZW1L86zR+zsjKxmyquiil6Ig6EYewpOAwMJXr61engbOe6MIr43GAyITVga3vLPlcbwu6U362iWOF64NuOXCHEghUKywF1WKTjI/WQQhhHcugkIjKFXsWzAg+xPeCa1qpvBMt0sOtcUUyzTGH4Qm/jl96DEOM2+94YiEnH2hGAwsbjff5pmeYajgRiCU/xG60ZchxXNUs/foJ9ycosTI3wZ+nYQquZ3RCfDJOYoEVTLr+D1xm/zPbd28svgjw1oyKdb0Qutxul45ExUSjpy0kuyROGSs4dJXDRGkS+JmCoXlJXIAdtd134A0IY+ha9jLIrcbYO+4uURm0elztutK/w5xDn8ZIeavuhqSpGJVObW2wAtqKDiz7fYPL/EaqwKPj003dI=
